In [2]:
import numpy as np
from numpy import array
#initial our S vectors
S = np.array([[1,1,1,-1]])

W = np.multiply(S.T,S)


def sn(n):
    for x in range(len(n)):
        if (n[x]<0):
            n[x] = -1
        else:
            n[x] = 1
    return n

def prid(n):
    out = np.multiply(n,W)
    out_oneD = [sum(i) for i in out]
    return array(out_oneD)

#print('\nFor A:')
#print(sn(prid(S)))
print(W)

[[ 1  1  1 -1]
 [ 1  1  1 -1]
 [ 1  1  1 -1]
 [-1 -1 -1  1]]


In [3]:
#now we add one mistake

S1 = np.array([[-1,1,1,-1]])
S2 = np.array([[1,-1,1,-1]])
S3 = np.array([[1,1,-1,-1]])
S4 = np.array([[1,1,1,1]])

print('\nFor S1:')
print(sn(prid(S1)))
print('\nFor S2:')
print(sn(prid(S2)))
print('\nFor S3:')
print(sn(prid(S3)))
print('\nFor S4:')
print(sn(prid(S4)))


For S1:
[ 1  1  1 -1]

For S2:
[ 1  1  1 -1]

For S3:
[ 1  1  1 -1]

For S4:
[ 1  1  1 -1]


In [4]:
#now we add two mistakes

S21 = np.array([[-1,-1,1,-1]])
S22 = np.array([[1,-1,-1,-1]])
S23 = np.array([[1,1,-1,1]])
S24 = np.array([[-1,1,1,1]])

print('\nFor S21:')
print(sn(prid(S1)))
print('\nFor S22:')
print(sn(prid(S2)))
print('\nFor S23:')
print(sn(prid(S3)))
print('\nFor S24:')
print(sn(prid(S4)))


For S21:
[ 1  1  1 -1]

For S22:
[ 1  1  1 -1]

For S23:
[ 1  1  1 -1]

For S24:
[ 1  1  1 -1]
